#pragma once

#include "sprites.h"

enum class Pokemon : uint8_t {
    Bulbasaur = 0,
    Ivysaur,
    Venusaur,
    Charmander,
    Charmeleon,
    Charizard,
    Squirtle,
    Wartortle,
    Blastoise,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    Rattata,
    Raticate,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    Sandshrew,
    Sandslash,
    Nidorana,
    Nidorina,
    Nidoqueen,
    Nidorano,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    Ninetales,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    Dugtrio,
    Meowth,
    Persian,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    Arcanine,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    Graveler,
    Golem,
    Ponyta,
    Rapidash,
    Slowpoke,
    Slowbro,
    Magnemite,
    Magneton,
    Farfetchd,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    Muk,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    Electrode,
    Exeggcute,
    Exeggutor,
    Cubone,
    Marowak,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    MrMime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp,
    Gyarados,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini,
    Dragonair,
    Dragonite,
    Mewtwo,
    Mew
};

const unsigned char *names[151] = {
        reinterpret_cast<const unsigned char *>("Bulbasaur"),
        reinterpret_cast<const unsigned char *>("Ivysaur"),
        reinterpret_cast<const unsigned char *>("Venusaur"),
        reinterpret_cast<const unsigned char *>("Charmander"),
        reinterpret_cast<const unsigned char *>("Charmeleon"),
        reinterpret_cast<const unsigned char *>("Charizard"),
        reinterpret_cast<const unsigned char *>("Squirtle"),
        reinterpret_cast<const unsigned char *>("Wartortle"),
        reinterpret_cast<const unsigned char *>("Blastoise"),
        reinterpret_cast<const unsigned char *>("Caterpie"),
        reinterpret_cast<const unsigned char *>("Metapod"),
        reinterpret_cast<const unsigned char *>("Butterfree"),
        reinterpret_cast<const unsigned char *>("Weedle"),
        reinterpret_cast<const unsigned char *>("Kakuna"),
        reinterpret_cast<const unsigned char *>("Beedrill"),
        reinterpret_cast<const unsigned char *>("Pidgey"),
        reinterpret_cast<const unsigned char *>("Pidgeotto"),
        reinterpret_cast<const unsigned char *>("Pidgeot"),
        reinterpret_cast<const unsigned char *>("Rattata"),
        reinterpret_cast<const unsigned char *>("Raticate"),
        reinterpret_cast<const unsigned char *>("Spearow"),
        reinterpret_cast<const unsigned char *>("Fearow"),
        reinterpret_cast<const unsigned char *>("Ekans"),
        reinterpret_cast<const unsigned char *>("Arbok"),
        reinterpret_cast<const unsigned char *>("Pikachu"),
        reinterpret_cast<const unsigned char *>("Raichu"),
        reinterpret_cast<const unsigned char *>("Sandshrew"),
        reinterpret_cast<const unsigned char *>("Sandslash"),
        reinterpret_cast<const unsigned char *>("Nidorana"), // ♀
        reinterpret_cast<const unsigned char *>("Nidorina"),
        reinterpret_cast<const unsigned char *>("Nidoqueen"),
        reinterpret_cast<const unsigned char *>("Nidorano"), // ♂
        reinterpret_cast<const unsigned char *>("Nidorino"),
        reinterpret_cast<const unsigned char *>("Nidoking"),
        reinterpret_cast<const unsigned char *>("Clefairy"),
        reinterpret_cast<const unsigned char *>("Clefable"),
        reinterpret_cast<const unsigned char *>("Vulpix"),
        reinterpret_cast<const unsigned char *>("Ninetales"),
        reinterpret_cast<const unsigned char *>("Jigglypuff"),
        reinterpret_cast<const unsigned char *>("Wigglytuff"),
        reinterpret_cast<const unsigned char *>("Zubat"),
        reinterpret_cast<const unsigned char *>("Golbat"),
        reinterpret_cast<const unsigned char *>("Oddish"),
        reinterpret_cast<const unsigned char *>("Gloom"),
        reinterpret_cast<const unsigned char *>("Vileplume"),
        reinterpret_cast<const unsigned char *>("Paras"),
        reinterpret_cast<const unsigned char *>("Parasect"),
        reinterpret_cast<const unsigned char *>("Venonat"),
        reinterpret_cast<const unsigned char *>("Venomoth"),
        reinterpret_cast<const unsigned char *>("Diglett"),
        reinterpret_cast<const unsigned char *>("Dugtrio"),
        reinterpret_cast<const unsigned char *>("Meowth"),
        reinterpret_cast<const unsigned char *>("Persian"),
        reinterpret_cast<const unsigned char *>("Psyduck"),
        reinterpret_cast<const unsigned char *>("Golduck"),
        reinterpret_cast<const unsigned char *>("Mankey"),
        reinterpret_cast<const unsigned char *>("Primeape"),
        reinterpret_cast<const unsigned char *>("Growlithe"),
        reinterpret_cast<const unsigned char *>("Arcanine"),
        reinterpret_cast<const unsigned char *>("Poliwag"),
        reinterpret_cast<const unsigned char *>("Poliwhirl"),
        reinterpret_cast<const unsigned char *>("Poliwrath"),
        reinterpret_cast<const unsigned char *>("Abra"),
        reinterpret_cast<const unsigned char *>("Kadabra"),
        reinterpret_cast<const unsigned char *>("Alakazam"),
        reinterpret_cast<const unsigned char *>("Machop"),
        reinterpret_cast<const unsigned char *>("Machoke"),
        reinterpret_cast<const unsigned char *>("Machamp"),
        reinterpret_cast<const unsigned char *>("Bellsprout"),
        reinterpret_cast<const unsigned char *>("Weepinbell"),
        reinterpret_cast<const unsigned char *>("Victreebel"),
        reinterpret_cast<const unsigned char *>("Tentacool"),
        reinterpret_cast<const unsigned char *>("Tentacruel"),
        reinterpret_cast<const unsigned char *>("Geodude"),
        reinterpret_cast<const unsigned char *>("Graveler"),
        reinterpret_cast<const unsigned char *>("Golem"),
        reinterpret_cast<const unsigned char *>("Ponyta"),
        reinterpret_cast<const unsigned char *>("Rapidash"),
        reinterpret_cast<const unsigned char *>("Slowpoke"),
        reinterpret_cast<const unsigned char *>("Slowbro"),
        reinterpret_cast<const unsigned char *>("Magnemite"),
        reinterpret_cast<const unsigned char *>("Magneton"),
        reinterpret_cast<const unsigned char *>("Farfetch'd"),
        reinterpret_cast<const unsigned char *>("Doduo"),
        reinterpret_cast<const unsigned char *>("Dodrio"),
        reinterpret_cast<const unsigned char *>("Seel"),
        reinterpret_cast<const unsigned char *>("Dewgong"),
        reinterpret_cast<const unsigned char *>("Grimer"),
        reinterpret_cast<const unsigned char *>("Muk"),
        reinterpret_cast<const unsigned char *>("Shellder"),
        reinterpret_cast<const unsigned char *>("Cloyster"),
        reinterpret_cast<const unsigned char *>("Gastly"),
        reinterpret_cast<const unsigned char *>("Haunter"),
        reinterpret_cast<const unsigned char *>("Gengar"),
        reinterpret_cast<const unsigned char *>("Onix"),
        reinterpret_cast<const unsigned char *>("Drowzee"),
        reinterpret_cast<const unsigned char *>("Hypno"),
        reinterpret_cast<const unsigned char *>("Krabby"),
        reinterpret_cast<const unsigned char *>("Kingler"),
        reinterpret_cast<const unsigned char *>("Voltorb"),
        reinterpret_cast<const unsigned char *>("Electrode"),
        reinterpret_cast<const unsigned char *>("Exeggcute"),
        reinterpret_cast<const unsigned char *>("Exeggutor"),
        reinterpret_cast<const unsigned char *>("Cubone"),
        reinterpret_cast<const unsigned char *>("Marowak"),
        reinterpret_cast<const unsigned char *>("Hitmonlee"),
        reinterpret_cast<const unsigned char *>("Hitmonchan"),
        reinterpret_cast<const unsigned char *>("Lickitung"),
        reinterpret_cast<const unsigned char *>("Koffing"),
        reinterpret_cast<const unsigned char *>("Weezing"),
        reinterpret_cast<const unsigned char *>("Rhyhorn"),
        reinterpret_cast<const unsigned char *>("Rhydon"),
        reinterpret_cast<const unsigned char *>("Chansey"),
        reinterpret_cast<const unsigned char *>("Tangela"),
        reinterpret_cast<const unsigned char *>("Kangaskhan"),
        reinterpret_cast<const unsigned char *>("Horsea"),
        reinterpret_cast<const unsigned char *>("Seadra"),
        reinterpret_cast<const unsigned char *>("Goldeen"),
        reinterpret_cast<const unsigned char *>("Seaking"),
        reinterpret_cast<const unsigned char *>("Staryu"),
        reinterpret_cast<const unsigned char *>("Starmie"),
        reinterpret_cast<const unsigned char *>("Mr. Mime"),
        reinterpret_cast<const unsigned char *>("Scyther"),
        reinterpret_cast<const unsigned char *>("Jynx"),
        reinterpret_cast<const unsigned char *>("Electabuzz"),
        reinterpret_cast<const unsigned char *>("Magmar"),
        reinterpret_cast<const unsigned char *>("Pinsir"),
        reinterpret_cast<const unsigned char *>("Tauros"),
        reinterpret_cast<const unsigned char *>("Magikarp"),
        reinterpret_cast<const unsigned char *>("Gyarados"),
        reinterpret_cast<const unsigned char *>("Lapras"),
        reinterpret_cast<const unsigned char *>("Ditto"),
        reinterpret_cast<const unsigned char *>("Eevee"),
        reinterpret_cast<const unsigned char *>("Vaporeon"),
        reinterpret_cast<const unsigned char *>("Jolteon"),
        reinterpret_cast<const unsigned char *>("Flareon"),
        reinterpret_cast<const unsigned char *>("Porygon"),
        reinterpret_cast<const unsigned char *>("Omanyte"),
        reinterpret_cast<const unsigned char *>("Omastar"),
        reinterpret_cast<const unsigned char *>("Kabuto"),
        reinterpret_cast<const unsigned char *>("Kabutops"),
        reinterpret_cast<const unsigned char *>("Aerodactyl"),
        reinterpret_cast<const unsigned char *>("Snorlax"),
        reinterpret_cast<const unsigned char *>("Articuno"),
        reinterpret_cast<const unsigned char *>("Zapdos"),
        reinterpret_cast<const unsigned char *>("Moltres"),
        reinterpret_cast<const unsigned char *>("Dratini"),
        reinterpret_cast<const unsigned char *>("Dragonair"),
        reinterpret_cast<const unsigned char *>("Dragonite"),
        reinterpret_cast<const unsigned char *>("Mewtwo"),
        reinterpret_cast<const unsigned char *>("Mew")
};

const unsigned char *getFrontSpriteByName(Pokemon pokemon) {
    return &Sprites::pokemon_sprite_sheet[static_cast<uint8_t>(pokemon) * (112 * 112 / 8 * 2)];
}

const unsigned char *getBackSpriteByName(Pokemon pokemon) {
    return &Sprites::pokemon_back_sprite_sheet[static_cast<uint8_t>(pokemon) * (96 * 84 / 8)];
}
